# Generated by Django 5.0.4 on 2024-04-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_Paciente', models.CharField(max_length=10)),
                ('nombre_Medico', models.CharField(max_length=150)),
            ],
        ),
    ]
