# Generated by Django 4.2.2 on 2024-05-01 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ReceteMedica', '0013_alter_receta_dni_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
