# Generated by Django 4.2.2 on 2024-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceteMedica', '0015_receta_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='hora',
            field=models.TimeField(),
        ),
    ]
