# Generated by Django 4.2.2 on 2024-04-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asegurado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asegurado',
            name='contraseña',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
