# Generated by Django 5.0.4 on 2024-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asegurado', '0002_alter_asegurado_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asegurado',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
