# Generated by Django 4.2.2 on 2024-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asegurado', '0003_alter_asegurado_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='asegurado',
            name='TipoSeguro',
            field=models.CharField(default='', max_length=50),
        ),
    ]
