# Generated by Django 4.2.2 on 2024-04-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asegurado', '0004_asegurado_tiposeguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='asegurado',
            name='ubicacion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
