# Generated by Django 4.2.2 on 2024-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asegurado', '0005_asegurado_ubicacion_alter_asegurado_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asegurado',
            name='Latitud',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='Longitud',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
