# Generated by Django 4.2.2 on 2024-04-13 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReceteMedica', '0002_receta_fecha'),
        ('RecetaMedicina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetamedicina',
            name='id_receta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ReceteMedica.receta'),
        ),
    ]
