# Generated by Django 4.2.2 on 2024-04-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecetaMedicina', '0002_alter_recetamedicina_id_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetamedicina',
            name='id_receta',
            field=models.CharField(max_length=10),
        ),
    ]
