# Generated by Django 4.2.2 on 2024-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_receta', models.CharField(max_length=8)),
                ('id_conductor', models.CharField(max_length=8)),
                ('id_administrador', models.CharField(max_length=8)),
                ('estatus', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
