# Generated by Django 4.2.2 on 2024-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='prioridad',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
