# Generated by Django 4.2.2 on 2024-06-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_pedido_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dni_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='firma_didigtal',
            field=models.TextField(null=True),
        ),
    ]
