# Generated by Django 4.2.2 on 2024-06-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_pedido_dni_img_pedido_firma_didigtal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='firma_didigtal',
            new_name='firma_digtal',
        ),
    ]
