# Generated by Django 4.2.2 on 2024-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_asegurado', models.CharField(max_length=8)),
                ('fecha', models.DateField()),
                ('nom_doctor', models.CharField(max_length=50)),
                ('co_pago', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
