# Generated by Django 4.2.2 on 2024-05-01 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Receta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='prioridad',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
