# Generated by Django 4.2.2 on 2024-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receta', '0002_receta_hora_receta_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='hora',
            field=models.TimeField(),
        ),
    ]
