# Generated by Django 4.2.2 on 2024-05-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receta', '0003_alter_receta_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='id_receta',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
