# Generated by Django 4.2.2 on 2024-05-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receta', '0004_receta_id_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='hora',
        ),
    ]
