# Generated by Django 4.2.2 on 2024-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicina', models.CharField(max_length=8)),
                ('nro_lote', models.CharField(max_length=10)),
                ('fec_entrada', models.DateField()),
                ('fec_venci', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('saldo', models.IntegerField()),
            ],
        ),
    ]
