# Generated by Django 4.2.2 on 2024-05-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kardex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='fec_entrada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
