# Generated by Django 4.2.2 on 2024-04-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicina',
            name='descripcion',
        ),
    ]
