# Generated by Django 4.2.2 on 2024-04-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conductor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='conductor',
        ),
    ]
