# Generated by Django 4.2.2 on 2024-07-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conductor', '0004_remove_conductor_ubicacion_conductor_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='licencia',
            field=models.CharField(default=51652, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='placa',
            field=models.CharField(default='1563', max_length=15),
            preserve_default=False,
        ),
    ]
