# Generated by Django 4.2.2 on 2024-04-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_alter_administrador_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
    ]
